"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Command = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var Command;
(function (Command) {
    Command[Command["SEND_DATA"] = 0] = "SEND_DATA";
    Command[Command["CHECK_MAILBOX"] = 1] = "CHECK_MAILBOX";
    Command[Command["GET_DATA"] = 2] = "GET_DATA";
    Command[Command["CHECK_HEARTBEAT"] = 3] = "CHECK_HEARTBEAT";
})(Command || (exports.Command = Command = {}));
