"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Platform = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var Platform;
(function (Platform) {
    Platform[Platform["APOLLO3"] = 0] = "APOLLO3";
    Platform[Platform["APOLLO4"] = 1] = "APOLLO4";
    Platform[Platform["APOLLO5"] = 2] = "APOLLO5";
})(Platform || (exports.Platform = Platform = {}));
