"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsbPacket = exports.UsbDataType = exports.Platform = exports.Command = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var command_js_1 = require("./usb/command.js");
Object.defineProperty(exports, "Command", { enumerable: true, get: function () { return command_js_1.Command; } });
var platform_js_1 = require("./usb/platform.js");
Object.defineProperty(exports, "Platform", { enumerable: true, get: function () { return platform_js_1.Platform; } });
var usb_data_type_js_1 = require("./usb/usb-data-type.js");
Object.defineProperty(exports, "UsbDataType", { enumerable: true, get: function () { return usb_data_type_js_1.UsbDataType; } });
var usb_packet_js_1 = require("./usb/usb-packet.js");
Object.defineProperty(exports, "UsbPacket", { enumerable: true, get: function () { return usb_packet_js_1.UsbPacket; } });
